### ISSUE TITLE
v2.1.0 not on NPM

### ISSUE THREAD

**Issue by simon-am** [mjmlio/gulp-mjml#18]
v2.1.0 is not updated on [npm](https://www.npmjs.com/package/gulp-mjml).
Sorry if this is just part of the release flow - just thought I'd report.

**Comment by ngarnier** [comment]
hey @simon-am, thanks for creating the issue. We'll push this asap on NPM, just dealing with a little pain regarding NPM accounts.

**Comment by maximepvrt** [comment]
please, quickly 😛

**Comment by ngarnier** [comment]
It's here 🎉  ! https://www.npmjs.com/package/gulp-mjml
