### ISSUE TITLE
Update mjml in package.json

### ISSUE THREAD

**Issue by eddjoke** [mjmlio/gulp-mjml#20]
Could you please update package.json to use mjml 3.3.0, since I see that there are some bugfixes in those latest minor releases (https://github.com/mjmlio/mjml/releases/tag/3.3.0)

**Comment by iRyusa** [comment]
Hello @eddjoke 

In the `package.json` we're using the `^` that will match any minor/patch version (3.X.X) so it will already install MJML 3.3.X

**Comment by eddjoke** [comment]
Yeah, I see. But when I install gulp-mjml and navigate to the node_modules, I see that package.json includes "mjml": "^3.0.0" as dependency, so it means that gulp-mjml uses the older mjml command line. Am I right?

I would prefer 3.3.X version there.

**Comment by iRyusa** [comment]
As said earlier `"^3.0.0" match the most recent version of MJML in the 3 branch, so it will be `3.3.X` now

**Comment by eddjoke** [comment]
Ok, so you can close my pull request. Thanks.
