### ISSUE TITLE
Includes not working with relative paths

### ISSUE THREAD

**Issue by cbrevik** [mjmlio/gulp-mjml#27]
As noted in https://github.com/mjmlio/gulp-mjml/issues/8#issuecomment-259505101 `mj-include` doesn't work with relative paths.

I see a PR where `filePath` is set on an object for includes, but I am not sure if it's used: https://github.com/mjmlio/gulp-mjml/pull/19/files#r130280996

Maybe the [`options` sent into `mjml2html`](https://github.com/mjmlio/gulp-mjml/blob/282f2625bd4bead9505e028c733fa21b63fe6296/src/index.js#L46) should be `localOptions` instead? 

**Edit**: I see there is an open PR for this #25

**Comment by iRyusa** [comment]
Hi @cbrevik 

We've released the 2.3 version of gulp-mjml that should fix this
