### ISSUE TITLE
Update to Version 3.3.3

### ISSUE THREAD

**Issue by Skinwalker** [mjmlio/gulp-mjml#28]
Are you planing to update MJML to the latest version?

**Comment by iRyusa** [comment]
Hi @Skinwalker 

We're using `^` char in package json so it should pickup the latest version available yet. You can try to reinstall it to update dependencies

**Comment by Skinwalker** [comment]
Tried that too - but all i got is:

Couldn't find any versions for "gulp-mjml" that matches "^"
? Please choose a version of "gulp-mjml" from this list: (Use arrow keys)
❯ 2.2.0 
  2.1.1 
  2.0.0 
  1.0.1 
  1.0.2 
  1.0.0 

In the npm repo the latest version is 2.2.0

**Comment by iRyusa** [comment]
You don't need to type`^`, in the package json mjml is listed as a dependency with `^` so it will pull the latest version available. Just remove all `gulp-mjml` versions and reinstall the latest

**Comment by Skinwalker** [comment]
I removed gulp-mjml ...

What do i add now?
gulp-mjml or mjml?

**Comment by iRyusa** [comment]
Just install gulp-mjml back

**Comment by Skinwalker** [comment]
alright - that worked - thank you!
