### ISSUE TITLE
update MJML

### ISSUE THREAD

**Issue by jimblue** [mjmlio/gulp-mjml#31]
Hello!

Is it possible MJML version to the last release?
There are plenty of fixes and new features.

Thank you

**Comment by iRyusa** [comment]
Hi @jimblue 
As we use the `^` on package.json it will fetch the last version available. So you can just get the last MJML version by reinstalling `gulp-mjml`

**Comment by jimblue** [comment]
Oh ok, that's great. Thanks for your fast answer !
