### ISSUE TITLE
Migrate to v4

### ISSUE THREAD

**Issue by mehrdaad** [mjmlio/gulp-mjml#34]
Mjml is on v4.0.0  but this package is on v4.0.0.  
Any plan to upgrade?

**Comment by iRyusa** [comment]
Both version are not dependent due to breaking changes, we're in process to upgrade every package in the ecosystem to MJML4 but this take some time. PR are also welcome

**Comment by brianespinosa** [comment]
Commenting here to express my interest in helping with this. If anyone decides to start work, let me know. I'll post here if I get a chance to start a branch and get working on this for anyone interested in helping.

**Comment by mattems** [comment]
I think the npm repo has not updated with the latest version as the master branch is different.

**Comment by jimblue** [comment]
Hi there!

The PR to solve this issue is merged and seems to work great.
Is it possible to publish a new release on NPM or there still something that need work?

Cheers

**Comment by mehrdaad** [comment]
Apparently a release to npm hasn't been published.

**Comment by iRyusa** [comment]
No need to post here + on the PR https://github.com/mjmlio/gulp-mjml/pull/35

We know that it's not released yet, we do our best to release every package in the ecosystem in MJML4 as fast as possible, thanks.

**Comment by mehrdaad** [comment]
V3.0.0 release 12 hours ago!

**Comment by mattems** [comment]
@mehrdaad ?? where is this release?

**Comment by mehrdaad** [comment]
@mattems https://www.npmjs.com/package/gulp-mjml?activeTab=versions
