### ISSUE TITLE
Latest version doesn't render everything in my MJML file

### ISSUE THREAD

**Issue by bramsmulders** [mjmlio/gulp-mjml#39]
I am using gulp-mjml `v3.0.0` on `Mac`, with Node `v8.11.1`.
I was trying to setup MJML and used the try it live template from: https://mjml.io/try-it-live

##### Entry file
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

##### Expected Behavior
The template renders just as expected, see: https://mjml.io/try-it-live

##### Actual Behavior
The template renders entirely empty, no hello world, no logo, no divider. Just some html with empty divs.

##### Steps to Reproduce
Just run it 😉

**Comment by kmcb777** [comment]
Hi @bramsmulders thanks for reporting this but i can't reproduce the issue on a fresh install. Did you upgrade from a previous version ? Maybe mjml v3 is still used somehow. Could you try wrapping the section in a `<mj-container>` ? If it works then that's the reason.

**Comment by bramsmulders** [comment]
Hi @kmcb777,

it seems that that was the case. My package lock was still pointing to an older version. Thnx for the swift response. 

Gr. Bram
