### ISSUE TITLE
Update mjml version

### ISSUE THREAD

**Issue by vctrfrnndz** [mjmlio/gulp-mjml#4]
The version of mjml used in this plugin has bugs such as `mj-column` overriding the width of an `mj-image` inside it. I had to switch to the `cli` utility, no success either running as an mjml engine.

**Comment by GuillaumeBadi** [comment]
You can provide your own mjml-engine to the gulp function : https://github.com/mjmlio/gulp-mjml/blob/master/src/index.js#L9 

```
import mjml from 'mjml'
import gMjml from 'gulp-mjml'

// ...
 .pipe(gMjml(mjml))
// ...
```

I am going to change the dependency for `latest`

**Comment by vctrfrnndz** [comment]
😕 Using the my own mjml engine didnt work for me, it just seemed to be using the same outdated version, my workarround was replicating your plugin inside my gulpfile, which did the trick
