### ISSUE TITLE
Choose Output File Extension

### ISSUE THREAD

**Issue by sinklair** [mjmlio/gulp-mjml#48]
Would be super helpful if there was an option to choose an output file extension other than html. I am creating handlebars files from mjml and VSCode treats them differently when the file extension is html instead of hbs

**Comment by sinklair** [comment]
Would be super helpful if there was an option to choose an output file extension other than html. I am creating handlebars files from mjml and VSCode treats them differently when the file extension is html instead of hbs

**Comment by iRyusa** [comment]
Relevant part of the code https://github.com/mjmlio/gulp-mjml/blob/master/src/index.js#L50 feel free to open a PR about this
