### ISSUE TITLE
gulp compiles only the first time

### ISSUE THREAD

**Issue by baronetto** [mjmlio/gulp-mjml#52]
Hi, I'm new to mjml and I'm trying to setup gulp. I've installed the plugin and added code in my gulpfile so that gulp watches for any changes to .mjml files

```
  return src(source, { base: "./" })
    .pipe(mjml())
    .on("error", reportError)
    .pipe(gulp.dest("."));
```

When I update a .mjml file, gulp does detect the changes and compiles the template but only once. When I make another change and hit save, nothing happens.

Any ideas what could be going on?

**Comment by iRyusa** [comment]
You need to use a plugin like gulp watch to have this behavior.

**Comment by baronetto** [comment]
Thank you for the quick reply! I do use watch and it gets intialized properly in the default task because. The problem is that any changes are detected only once for mjml whereas for other tasks (sass, js etc.) it works just fine after saving any change.
```
watch("templates/**/*.mjml", function() {
    mjml();   
  });
```

**Comment by iRyusa** [comment]
Just share your entire gulp file here we can’t really help you.

**Comment by iRyusa** [comment]
This is not how `watch` works : https://www.npmjs.com/package/gulp-watch#usage
