### ISSUE TITLE
Bump mjml dependency to latest release?

### ISSUE THREAD

**Issue by probablyabear** [mjmlio/gulp-mjml#54]
Would it be possible to bump the version of MJML used in this to the latest release?

**Comment by iRyusa** [comment]
If you reinstall it, it should grab the latest version available already

**Comment by probablyabear** [comment]
Thanks @iRyusa. I reinstalled it, and double checked its package.json. Looks like it's setup to pull in the latest minor version since 4.0.0:

```
"dependencies": {
    "mjml": "^4.0.0",
    "plugin-error": "^1.0.1",
    "replace-ext": "^1.0.0",
    "through2": "^3.0.1"
  },
```

Just want to be sure I can take advantage of the newer releases of mjml while using this in my gulp workflow.

**Comment by iRyusa** [comment]
Carret on npm will match latest non major version, so it shouldn’t be an issue check if you have any lock filE in your project

**Comment by probablyabear** [comment]
You're right, thanks for the sanity check!
