### ISSUE TITLE
I dont think mj-html-attributes are registered? 

### ISSUE THREAD

**Issue by Chrisedmo** [mjmlio/gulp-mjml#59]
Hi I'm trying something out with mj-html-attributes and it is not working. It does nothing however when i just run my files via 
`mjml [input] -o [output]`

I get the following: 
```
No matching component for tag : mj-html-attributes
... (mj-html-attributes) — Element mj-html-attributes doesn't exist or is not registered
... (mj-selector) — Element mj-selector doesn't exist or is not registered
```

**Comment by iRyusa** [comment]
You forgot to install the beta ?

**Comment by Chrisedmo** [comment]
@iRyusa Thanks for coming back - but Beta? Where is this?

**Comment by iRyusa** [comment]
The feature is only available in 4.7 beta branch use @next tag on npm to install it.

**Comment by Chrisedmo** [comment]
Thanks i've updated my package.json and still getting the same error. Very odd.

**Comment by iRyusa** [comment]
Remove your node module and ensure you have the 4.7 in node modules
