### ISSUE TITLE
Getting deprecation warning when turning minify option on

### ISSUE THREAD

**Issue by locnguyen** [mjmlio/gulp-mjml#62]
This is how I defined my gulp task

```
gulp.task('default', () => {
    return gulp.src('./src/**/*.mjml')
        .pipe(mjml(null, {minify: true}))
        .on('error', e => console.log(e))
        .pipe(gulp.dest('./build'))
```

When running it I get this warning

`"minify" option is deprecated in mjml-core and only available in mjml cli.`

I suspect upgrading the mjml dependency to 4.8.x may fix it because of https://github.com/mjmlio/mjml/pull/2059

I will open that PR after testing.

**Comment by iRyusa** [comment]
It's a warning from MJML 4.8 (and gulp mjml will catch the latest available version)

We'll provide a migration guide on gulp-mjml when it will be completely removed.
