### ISSUE TITLE
Bug: should emit errors, not throw

### ISSUE THREAD

**Issue by Lendar** [mjmlio/gulp-mjml#7]
Usecase: don't crash `gulp.watch` on errors.

I suppose it should not throw, but it should emit error instead. Then error could be caught by a wrapper that will display it to the user.

---

Steps to reproduce:

``` js
// gulpfile.js
var gulp = require('gulp');
var mjml = require('gulp-mjml')

gulp.task('build', function () {
  gulp.src('./*.mjml')
    .pipe(mjml())
    .pipe(gulp.dest('./html'))
});

gulp.task('watch', function () {
  return gulp.watch('./*.mjml', ['build'])
})
```

And mjml file with syntax error:

```
<mjml>
```

**Comment by Apercu** [comment]
Although not the best experience I must admit, I still believe this is mostly an issue with gulp itself that they plan to fix in a future release. You might want to have a look at [plumber](https://github.com/floatdrop/gulp-plumber) if you don't know about it, and will serve the purpose you want to achieve.

Given the inactivity on the side of gulp though, considering to remove the throw should also be fine if the plumber solution is deemed too expensive.

<sub>$0.02</dub>

**Comment by ngarnier** [comment]
Hi, late reply but as explained by @Apercu, we don't think this should be handled by `gulp-mjml`.
