### ISSUE TITLE
Problem with mj-include

### ISSUE THREAD

**Issue by martinbertinat** [mjmlio/gulp-mjml#8]
Hi, first thanks for the work.

I'm getting: 

Starting 'mjml'...
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './header.mjml'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at /home/martin/vagrants/scotch/public/posada/node_modules/mjml-core/lib/includeExternal.js:25:33

In my mjml template I have: <mj-include path="./header.mjml"></mj-include>

Node version: v5.12.0

If you need more info just tell me. thanks

**Comment by ngarnier** [comment]
hey @martinbertinat, sorry for the late answer here. Was your issue solved in the meantime?

If not, can you please share the MJML causing this issue?

**Comment by martinbertinat** [comment]
Hello, I think it was a problem with the paths I used for the includes.

Thanks

**Comment by jkudish** [comment]
@martinbertinat do you mind sharing how you solved this? i've tried every path that could make sense and I can't get it to work 👎 

Thanks!

**Comment by jkudish** [comment]
Got it to work, after posting, of course.

Had to include the full path from project root (which I had tried but forgot the `./` at the start the first time). I wish the path was relative...

**Comment by martinbertinat** [comment]
Hi @jkudish. I was writing that!

Thanks for posting the solution
